<?php

/**
 * This class displays an array of entities by drawing a set of Tiles (generated by the EntityTileView class).
 */
class EntitiesView {
	
	// The entities to display.
	private $entities;
	
	// The logger instance.
	private $logger;
	
	function __construct($entities) {
		$this->logger = $GLOBALS['logger'];
		$this->entities = $entities;
	}
	
	public function getContent($content = '') {
		
		$this->logger->debug('Generating content for ['.count($this->entities).'] entities.');
		
		$content = '<div style="width: 100%;" id="entities" class="entities-view">';
		
		foreach ($this->entities as $entity) {
			$entity_tile_view = new EntityTileView($entity);
			$content .= $entity_tile_view->getContent();
		}
		
		$content .= '</div>';
// 		$content .= '<script type="text/javascript">jQuery(window).ready(function(){wordlift.client.setupUI();});</script>';
		
		return $content;
		
	}
	
}


?>