DELETE { <POST_URI> <http://schema.org/headline> ?o } WHERE { <POST_URI> <http://schema.org/headline> ?o }; 
DELETE { ?s <http://schema.org/headline> <POST_URI> } WHERE { ?s <http://schema.org/headline> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/url> ?o } WHERE { <POST_URI> <http://schema.org/url> ?o }; 
DELETE { ?s <http://schema.org/url> <POST_URI> } WHERE { ?s <http://schema.org/url> <POST_URI> }; 
DELETE { <POST_URI> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o } WHERE { <POST_URI> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o }; 
DELETE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <POST_URI> } WHERE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <POST_URI> }; 
DELETE { <POST_URI> <http://purl.org/dc/terms/references> ?o } WHERE { <POST_URI> <http://purl.org/dc/terms/references> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/references> <POST_URI> } WHERE { ?s <http://purl.org/dc/terms/references> <POST_URI> }; 
DELETE { <POST_URI> <http://www.w3.org/2000/01/rdf-schema#label> ?o } WHERE { <POST_URI> <http://www.w3.org/2000/01/rdf-schema#label> ?o }; 
DELETE { ?s <http://www.w3.org/2000/01/rdf-schema#label> <POST_URI> } WHERE { ?s <http://www.w3.org/2000/01/rdf-schema#label> <POST_URI> }; 
DELETE { <POST_URI> <http://purl.org/dc/terms/title> ?o } WHERE { <POST_URI> <http://purl.org/dc/terms/title> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/title> <POST_URI> } WHERE { ?s <http://purl.org/dc/terms/title> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/name> ?o } WHERE { <POST_URI> <http://schema.org/name> ?o }; 
DELETE { ?s <http://schema.org/name> <POST_URI> } WHERE { ?s <http://schema.org/name> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/alternateName> ?o } WHERE { <POST_URI> <http://schema.org/alternateName> ?o }; 
DELETE { ?s <http://schema.org/alternateName> <POST_URI> } WHERE { ?s <http://schema.org/alternateName> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/description> ?o } WHERE { <POST_URI> <http://schema.org/description> ?o }; 
DELETE { ?s <http://schema.org/description> <POST_URI> } WHERE { ?s <http://schema.org/description> <POST_URI> }; 
DELETE { <POST_URI> <http://www.w3.org/2002/07/owl#sameAs> ?o } WHERE { <POST_URI> <http://www.w3.org/2002/07/owl#sameAs> ?o }; 
DELETE { ?s <http://www.w3.org/2002/07/owl#sameAs> <POST_URI> } WHERE { ?s <http://www.w3.org/2002/07/owl#sameAs> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/sameAs> ?o } WHERE { <POST_URI> <http://schema.org/sameAs> ?o }; 
DELETE { ?s <http://schema.org/sameAs> <POST_URI> } WHERE { ?s <http://schema.org/sameAs> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/image> ?o } WHERE { <POST_URI> <http://schema.org/image> ?o }; 
DELETE { ?s <http://schema.org/image> <POST_URI> } WHERE { ?s <http://schema.org/image> <POST_URI> }; 
DELETE { <POST_URI> <http://purl.org/dc/terms/relation> ?o } WHERE { <POST_URI> <http://purl.org/dc/terms/relation> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/relation> <POST_URI> } WHERE { ?s <http://purl.org/dc/terms/relation> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/author> ?o } WHERE { <POST_URI> <http://schema.org/author> ?o }; 
DELETE { ?s <http://schema.org/author> <POST_URI> } WHERE { ?s <http://schema.org/author> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/startDate> ?o } WHERE { <POST_URI> <http://schema.org/startDate> ?o }; 
DELETE { ?s <http://schema.org/startDate> <POST_URI> } WHERE { ?s <http://schema.org/startDate> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/endDate> ?o } WHERE { <POST_URI> <http://schema.org/endDate> ?o }; 
DELETE { ?s <http://schema.org/endDate> <POST_URI> } WHERE { ?s <http://schema.org/endDate> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/location> ?o } WHERE { <POST_URI> <http://schema.org/location> ?o }; 
DELETE { ?s <http://schema.org/location> <POST_URI> } WHERE { ?s <http://schema.org/location> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/performer> ?o } WHERE { <POST_URI> <http://schema.org/performer> ?o }; 
DELETE { ?s <http://schema.org/performer> <POST_URI> } WHERE { ?s <http://schema.org/performer> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/offers> ?o } WHERE { <POST_URI> <http://schema.org/offers> ?o }; 
DELETE { ?s <http://schema.org/offers> <POST_URI> } WHERE { ?s <http://schema.org/offers> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/legalName> ?o } WHERE { <POST_URI> <http://schema.org/legalName> ?o }; 
DELETE { ?s <http://schema.org/legalName> <POST_URI> } WHERE { ?s <http://schema.org/legalName> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/founder> ?o } WHERE { <POST_URI> <http://schema.org/founder> ?o }; 
DELETE { ?s <http://schema.org/founder> <POST_URI> } WHERE { ?s <http://schema.org/founder> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/email> ?o } WHERE { <POST_URI> <http://schema.org/email> ?o }; 
DELETE { ?s <http://schema.org/email> <POST_URI> } WHERE { ?s <http://schema.org/email> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/telephone> ?o } WHERE { <POST_URI> <http://schema.org/telephone> ?o }; 
DELETE { ?s <http://schema.org/telephone> <POST_URI> } WHERE { ?s <http://schema.org/telephone> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/knows> ?o } WHERE { <POST_URI> <http://schema.org/knows> ?o }; 
DELETE { ?s <http://schema.org/knows> <POST_URI> } WHERE { ?s <http://schema.org/knows> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/birthDate> ?o } WHERE { <POST_URI> <http://schema.org/birthDate> ?o }; 
DELETE { ?s <http://schema.org/birthDate> <POST_URI> } WHERE { ?s <http://schema.org/birthDate> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/birthPlace> ?o } WHERE { <POST_URI> <http://schema.org/birthPlace> ?o }; 
DELETE { ?s <http://schema.org/birthPlace> <POST_URI> } WHERE { ?s <http://schema.org/birthPlace> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/affiliation> ?o } WHERE { <POST_URI> <http://schema.org/affiliation> ?o }; 
DELETE { ?s <http://schema.org/affiliation> <POST_URI> } WHERE { ?s <http://schema.org/affiliation> <POST_URI> }; 
DELETE { <POST_URI/address> <http://schema.org/streetAddress> ?o } WHERE { <POST_URI/address> <http://schema.org/streetAddress> ?o }; 
DELETE { ?s <http://schema.org/streetAddress> <POST_URI/address> } WHERE { ?s <http://schema.org/streetAddress> <POST_URI/address> }; 
DELETE { <POST_URI/address> <http://schema.org/postOfficeBoxNumber> ?o } WHERE { <POST_URI/address> <http://schema.org/postOfficeBoxNumber> ?o }; 
DELETE { ?s <http://schema.org/postOfficeBoxNumber> <POST_URI/address> } WHERE { ?s <http://schema.org/postOfficeBoxNumber> <POST_URI/address> }; 
DELETE { <POST_URI/address> <http://schema.org/postalCode> ?o } WHERE { <POST_URI/address> <http://schema.org/postalCode> ?o }; 
DELETE { ?s <http://schema.org/postalCode> <POST_URI/address> } WHERE { ?s <http://schema.org/postalCode> <POST_URI/address> }; 
DELETE { <POST_URI/address> <http://schema.org/addressLocality> ?o } WHERE { <POST_URI/address> <http://schema.org/addressLocality> ?o }; 
DELETE { ?s <http://schema.org/addressLocality> <POST_URI/address> } WHERE { ?s <http://schema.org/addressLocality> <POST_URI/address> }; 
DELETE { <POST_URI/address> <http://schema.org/addressRegion> ?o } WHERE { <POST_URI/address> <http://schema.org/addressRegion> ?o }; 
DELETE { ?s <http://schema.org/addressRegion> <POST_URI/address> } WHERE { ?s <http://schema.org/addressRegion> <POST_URI/address> }; 
DELETE { <POST_URI/address> <http://schema.org/addressCountry> ?o } WHERE { <POST_URI/address> <http://schema.org/addressCountry> ?o }; 
DELETE { ?s <http://schema.org/addressCountry> <POST_URI/address> } WHERE { ?s <http://schema.org/addressCountry> <POST_URI/address> }; 
DELETE { <POST_URI> <http://schema.org/address> <POST_URI/address> .  } WHERE { <POST_URI> <http://schema.org/address> <POST_URI/address> .  }; 
DELETE { <POST_URI/address> a <http://schema.org/PostalAddress> .  } WHERE { <POST_URI/address> a <http://schema.org/PostalAddress> .  }; 
DELETE { <POST_URI> <http://schema.org/recipeCuisine> ?o } WHERE { <POST_URI> <http://schema.org/recipeCuisine> ?o }; 
DELETE { ?s <http://schema.org/recipeCuisine> <POST_URI> } WHERE { ?s <http://schema.org/recipeCuisine> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/recipeIngredient> ?o } WHERE { <POST_URI> <http://schema.org/recipeIngredient> ?o }; 
DELETE { ?s <http://schema.org/recipeIngredient> <POST_URI> } WHERE { ?s <http://schema.org/recipeIngredient> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/recipeInstructions> ?o } WHERE { <POST_URI> <http://schema.org/recipeInstructions> ?o }; 
DELETE { ?s <http://schema.org/recipeInstructions> <POST_URI> } WHERE { ?s <http://schema.org/recipeInstructions> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/recipeYield> ?o } WHERE { <POST_URI> <http://schema.org/recipeYield> ?o }; 
DELETE { ?s <http://schema.org/recipeYield> <POST_URI> } WHERE { ?s <http://schema.org/recipeYield> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/prepTime> ?o } WHERE { <POST_URI> <http://schema.org/prepTime> ?o }; 
DELETE { ?s <http://schema.org/prepTime> <POST_URI> } WHERE { ?s <http://schema.org/prepTime> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/cookTime> ?o } WHERE { <POST_URI> <http://schema.org/cookTime> ?o }; 
DELETE { ?s <http://schema.org/cookTime> <POST_URI> } WHERE { ?s <http://schema.org/cookTime> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/totalTime> ?o } WHERE { <POST_URI> <http://schema.org/totalTime> ?o }; 
DELETE { ?s <http://schema.org/totalTime> <POST_URI> } WHERE { ?s <http://schema.org/totalTime> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/availability> ?o } WHERE { <POST_URI> <http://schema.org/availability> ?o }; 
DELETE { ?s <http://schema.org/availability> <POST_URI> } WHERE { ?s <http://schema.org/availability> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/availabilityStarts> ?o } WHERE { <POST_URI> <http://schema.org/availabilityStarts> ?o }; 
DELETE { ?s <http://schema.org/availabilityStarts> <POST_URI> } WHERE { ?s <http://schema.org/availabilityStarts> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/availabilityEnds> ?o } WHERE { <POST_URI> <http://schema.org/availabilityEnds> ?o }; 
DELETE { ?s <http://schema.org/availabilityEnds> <POST_URI> } WHERE { ?s <http://schema.org/availabilityEnds> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/inventoryLevel> ?o } WHERE { <POST_URI> <http://schema.org/inventoryLevel> ?o }; 
DELETE { ?s <http://schema.org/inventoryLevel> <POST_URI> } WHERE { ?s <http://schema.org/inventoryLevel> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/price> ?o } WHERE { <POST_URI> <http://schema.org/price> ?o }; 
DELETE { ?s <http://schema.org/price> <POST_URI> } WHERE { ?s <http://schema.org/price> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/priceCurrency> ?o } WHERE { <POST_URI> <http://schema.org/priceCurrency> ?o }; 
DELETE { ?s <http://schema.org/priceCurrency> <POST_URI> } WHERE { ?s <http://schema.org/priceCurrency> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/validFrom> ?o } WHERE { <POST_URI> <http://schema.org/validFrom> ?o }; 
DELETE { ?s <http://schema.org/validFrom> <POST_URI> } WHERE { ?s <http://schema.org/validFrom> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/priceValidUntil> ?o } WHERE { <POST_URI> <http://schema.org/priceValidUntil> ?o }; 
DELETE { ?s <http://schema.org/priceValidUntil> <POST_URI> } WHERE { ?s <http://schema.org/priceValidUntil> <POST_URI> }; 
DELETE { <POST_URI> <http://schema.org/itemOffered> ?o } WHERE { <POST_URI> <http://schema.org/itemOffered> ?o }; 
DELETE { ?s <http://schema.org/itemOffered> <POST_URI> } WHERE { ?s <http://schema.org/itemOffered> <POST_URI> }; 
