DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/2000/01/rdf-schema#label> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/2000/01/rdf-schema#label> ?o }; 
DELETE { ?s <http://www.w3.org/2000/01/rdf-schema#label> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://www.w3.org/2000/01/rdf-schema#label> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/title> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/title> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/title> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://purl.org/dc/terms/title> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/url> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/url> ?o }; 
DELETE { ?s <http://schema.org/url> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/url> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/description> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/description> ?o }; 
DELETE { ?s <http://schema.org/description> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/description> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/2002/07/owl#sameAs> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/2002/07/owl#sameAs> ?o }; 
DELETE { ?s <http://www.w3.org/2002/07/owl#sameAs> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://www.w3.org/2002/07/owl#sameAs> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o }; 
DELETE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/image> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/image> ?o }; 
DELETE { ?s <http://schema.org/image> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/image> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/relation> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/relation> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/relation> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://purl.org/dc/terms/relation> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/author> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/author> ?o }; 
DELETE { ?s <http://schema.org/author> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/author> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/startDate> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/startDate> ?o }; 
DELETE { ?s <http://schema.org/startDate> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/startDate> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/endDate> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/endDate> ?o }; 
DELETE { ?s <http://schema.org/endDate> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/endDate> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/location> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/location> ?o }; 
DELETE { ?s <http://schema.org/location> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/location> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/performer> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/performer> ?o }; 
DELETE { ?s <http://schema.org/performer> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/performer> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/offers> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/offers> ?o }; 
DELETE { ?s <http://schema.org/offers> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/offers> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/legalName> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/legalName> ?o }; 
DELETE { ?s <http://schema.org/legalName> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/legalName> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/founder> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/founder> ?o }; 
DELETE { ?s <http://schema.org/founder> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/founder> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/email> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/email> ?o }; 
DELETE { ?s <http://schema.org/email> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/email> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/telephone> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/telephone> ?o }; 
DELETE { ?s <http://schema.org/telephone> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/telephone> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/knows> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/knows> ?o }; 
DELETE { ?s <http://schema.org/knows> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/knows> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/birthDate> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/birthDate> ?o }; 
DELETE { ?s <http://schema.org/birthDate> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/birthDate> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/birthPlace> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/birthPlace> ?o }; 
DELETE { ?s <http://schema.org/birthPlace> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/birthPlace> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/affiliation> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/affiliation> ?o }; 
DELETE { ?s <http://schema.org/affiliation> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/affiliation> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/streetAddress> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/streetAddress> ?o }; 
DELETE { ?s <http://schema.org/streetAddress> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/streetAddress> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/postOfficeBoxNumber> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/postOfficeBoxNumber> ?o }; 
DELETE { ?s <http://schema.org/postOfficeBoxNumber> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/postOfficeBoxNumber> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/postalCode> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/postalCode> ?o }; 
DELETE { ?s <http://schema.org/postalCode> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/postalCode> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressLocality> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressLocality> ?o }; 
DELETE { ?s <http://schema.org/addressLocality> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/addressLocality> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressRegion> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressRegion> ?o }; 
DELETE { ?s <http://schema.org/addressRegion> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/addressRegion> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressCountry> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> <http://schema.org/addressCountry> ?o }; 
DELETE { ?s <http://schema.org/addressCountry> <http://data.redlink.io/91/test2/post/post_title_24/address> } WHERE { ?s <http://schema.org/addressCountry> <http://data.redlink.io/91/test2/post/post_title_24/address> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/address> <http://data.redlink.io/91/test2/post/post_title_24/address> .  } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/address> <http://data.redlink.io/91/test2/post/post_title_24/address> .  }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24/address> a <http://schema.org/PostalAddress> .  } WHERE { <http://data.redlink.io/91/test2/post/post_title_24/address> a <http://schema.org/PostalAddress> .  }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/recipeCuisine> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/recipeCuisine> ?o }; 
DELETE { ?s <http://schema.org/recipeCuisine> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/recipeCuisine> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/recipeIngredient> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/recipeIngredient> ?o }; 
DELETE { ?s <http://schema.org/recipeIngredient> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/recipeIngredient> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/prepTime> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/prepTime> ?o }; 
DELETE { ?s <http://schema.org/prepTime> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/prepTime> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/cookTime> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/cookTime> ?o }; 
DELETE { ?s <http://schema.org/cookTime> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/cookTime> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/totalTime> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/totalTime> ?o }; 
DELETE { ?s <http://schema.org/totalTime> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/totalTime> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/headline> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/headline> ?o }; 
DELETE { ?s <http://schema.org/headline> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/headline> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/references> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://purl.org/dc/terms/references> ?o }; 
DELETE { ?s <http://purl.org/dc/terms/references> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://purl.org/dc/terms/references> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availability> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availability> ?o }; 
DELETE { ?s <http://schema.org/availability> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/availability> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availabilityStarts> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availabilityStarts> ?o }; 
DELETE { ?s <http://schema.org/availabilityStarts> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/availabilityStarts> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availabilityEnds> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/availabilityEnds> ?o }; 
DELETE { ?s <http://schema.org/availabilityEnds> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/availabilityEnds> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/inventoryLevel> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/inventoryLevel> ?o }; 
DELETE { ?s <http://schema.org/inventoryLevel> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/inventoryLevel> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/price> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/price> ?o }; 
DELETE { ?s <http://schema.org/price> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/price> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/priceCurrency> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/priceCurrency> ?o }; 
DELETE { ?s <http://schema.org/priceCurrency> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/priceCurrency> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/validFrom> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/validFrom> ?o }; 
DELETE { ?s <http://schema.org/validFrom> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/validFrom> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/priceValidUntil> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/priceValidUntil> ?o }; 
DELETE { ?s <http://schema.org/priceValidUntil> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/priceValidUntil> <http://data.redlink.io/91/test2/post/post_title_24> }; 
DELETE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/itemOffered> ?o } WHERE { <http://data.redlink.io/91/test2/post/post_title_24> <http://schema.org/itemOffered> ?o }; 
DELETE { ?s <http://schema.org/itemOffered> <http://data.redlink.io/91/test2/post/post_title_24> } WHERE { ?s <http://schema.org/itemOffered> <http://data.redlink.io/91/test2/post/post_title_24> }; 
