<?php


define('WORDLIFT_20_FIELD_PREFIX',					'io-wordlift-');
define('WORDLIFT_20_FIELD_SCHEMA_TYPE',				WORDLIFT_20_FIELD_PREFIX.'schema-type');
define('WORDLIFT_20_FIELD_IMAGE',					WORDLIFT_20_FIELD_PREFIX.'image');
define('WORDLIFT_20_FIELD_LATITUDE',				WORDLIFT_20_FIELD_PREFIX.'geo-latitude');
define('WORDLIFT_20_FIELD_LONGITUDE',				WORDLIFT_20_FIELD_PREFIX.'geo-longitude');

?>