PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> rdfs:label ?o }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> rdfs:label ?o };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> owl:sameAs ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> owl:sameAs ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> schema:description ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> schema:description ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> schema:url ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> schema:url ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> a ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> a ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> dct:relation ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> dct:relation ?o . };
    INSERT DATA { <http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> owl:sameAs <http://dbpedia.org/resource/Linked_data> .
<http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> rdfs:label "Linked Open Data"@en .
<http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> schema:url <http://example.org/?post_type=entity&p=1978> .
<http://data.redlink.io/353/wordlift-tests-php-5-4-wp-3-8-ms-0/entity/Linked_Open_Data> a <http://schema.org/Thing> .
 }
