PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> rdfs:label ?o }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> rdfs:label ?o };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> owl:sameAs ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> owl:sameAs ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:description ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:description ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:url ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:url ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> a ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> a ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> dct:relation ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> dct:relation ?o . };
    DELETE { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:image ?o . }
    WHERE  { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:image ?o . };
    INSERT DATA { <http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> owl:sameAs <http://rdf.freebase.com/ns/m.06c62> . 
<http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> rdfs:label "Rome"@en . 
<http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> schema:url <http://example.org/?post_type=entity&p=13> . 
<http://data.redlink.io/353/wordlift-tests-php-5-3-wp-3-8-ms-0/entity/Rome> a <http://schema.org/Place> . 
 }
