<?php

/**
 */
class Wordlift_Sanitizer_Test extends Wordlift_Unit_Test_Case {

	function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub

		// We don't need to check the remote Linked Data store.
		$this->turn_off_entity_push();

	}


	public function test() {


		$this->assertNotNull( Wordlift_Sanitizer::sanitize_url( 'http://dbpedia.org/resource/Huttau' ) );

		$this->assertNotNull( Wordlift_Sanitizer::sanitize_url( 'http://dbpedia.org/resource/Hüttau' ) );


	}

}
