<?php
/**
 * Tests the wordlift test jsonld adapter class.
 *
 * @since 3.26.0
 * @author Naveen Muthusamy <naveen@wordlift.io>
 * @package    Wordlift
 * @subpackage Wordlift/tests
 */

class Wordlift_Term_Jsonld_Adapter_Test extends Wordlift_Unit_Test_Case {
	/**
	 * @var Wordlift_Term_JsonLd_Adapter instance.
	 */
	private $adapter;

	function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->adapter = new Wordlift_Term_JsonLd_Adapter( Wordlift_Entity_Uri_Service::get_instance(), Wordlift_Jsonld_Service::get_instance() );
	}

	public function test_if_less_than_2_posts_are_present_then_dont_alter_the_jsonld() {
		// lets create a category
		$category_id = wp_insert_category( array( 'cat_name' => 'foo' ) );
		$result      = $this->adapter->get_carousel_jsonld( 'category', $category_id, array() );
		$this->assertEquals( $result, array() );
	}

}