<?php

use Wordlift\Post_Excerpt\Post_Excerpt_Rest_Controller;

/**
 * Tests: Tests the Post excerpt rest controller.
 * @since 3.26.0
 * @package wordlift
 * @subpackage wordlift/tests
 *
 */

class Post_Excerpt_REST_Controller_Test extends Wordlift_Unit_Test_Case {

	/**
	 * @var Post_Excerpt_Rest_Controller
	 */
	private $rest_instance;

	/**
	 * @var string
	 */
	private $post_excerpt_rest_route;
	/**
	 * @var WP_REST_Server
	 */
	private $server;

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->rest_instance = new Post_Excerpt_Rest_Controller();
		$this->post_excerpt_rest_route = "/wordlift/v1/post-excerpt";
		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		$this->server   = $wp_rest_server;
		//$this->rest_instance->register_routes();
		do_action( 'rest_api_init' );
	}

	/**
	 * Try mimicking a request without valid authentication
	 */
	public function test_if_request_without_proper_authentication_should_fail() {
		$post_id = $this->factory()->post->create();
		$url  = $this->post_excerpt_rest_route . '/' . $post_id;
		var_dump($url);
		$request   = new WP_REST_Request( 'POST', $url);
		$request->set_header( 'content-type', 'application/json' );
		$request->set_body( wp_json_encode( array() ) );
		$response  = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		$this->assertEquals($response_data['code'], 'rest_forbidden');
	}

}