<?php
/**
 * Tests the wordlift test jsonld adapter class.
 *
 * @since 3.26.0
 * @author Naveen Muthusamy <naveen@wordlift.io>
 * @package    Wordlift
 * @subpackage Wordlift/tests
 */

class Wordlift_Term_Jsonld_Adapter_Test extends Wordlift_Unit_Test_Case {
	/**
	 * @var Wordlift_Term_JsonLd_Adapter instance.
	 */
	private $adapter;

	function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->adapter = new Wordlift_Term_JsonLd_Adapter();
	}

}