<?php

use Wordlift\Post_Excerpt\Post_Excerpt_Rest_Controller;

/**
 * Tests: Tests the Post excerpt rest controller.
 * @since 3.26.0
 * @package wordlift
 * @subpackage wordlift/tests
 *
 */
class Post_Excerpt_REST_Controller_Test extends Wordlift_Unit_Test_Case {

	/**
	 * @var Post_Excerpt_Rest_Controller
	 */
	private $rest_instance;

	/**
	 * @var string
	 */
	private $post_excerpt_rest_route;
	/**
	 * @var WP_REST_Server
	 */
	private $server;

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->rest_instance           = new Post_Excerpt_Rest_Controller();
		$this->post_excerpt_rest_route = "/wordlift/v1/post-excerpt";
		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		$this->server   = $wp_rest_server;
		//$this->rest_instance->register_routes();
		do_action( 'rest_api_init' );
	}

	/**
	 * Try mimicking a request without valid authentication
	 */
	public function test_if_request_without_proper_authentication_should_fail() {
		$post_id = $this->factory()->post->create();
		$url     = $this->post_excerpt_rest_route . '/' . $post_id;
		$request = new WP_REST_Request( 'POST', $url );
		$request->set_header( 'content-type', 'application/json' );
		$request->set_body( wp_json_encode( array( 'post_body' => 'foo' ) ) );
		$response      = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		$this->assertEquals( $response_data['code'], 'rest_forbidden' );
	}


	public function test_if_post_body_is_not_present_then_request_should_be_invalid() {
		$user_id = $this->factory->user->create( array( 'role' => 'author' ) );
		wp_set_current_user( $user_id );
		$post_id = $this->factory->post->create();
		$url     = $this->post_excerpt_rest_route . '/' . $post_id;
		$request = new WP_REST_Request( 'POST', $url );
		$request->set_header( 'content-type', 'application/json' );
		$request->set_body( wp_json_encode( array() ) );
		$response      = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		$this->assertEquals( $response_data['code'], 'rest_missing_callback_param' );
	}

	/**
	 * This test uses wp_remote_post in the code, it should be mocked once it passes.
	 */
	public function test_if_valid_content_posted_should_return_valid_excerpt() {
		$valid_content = <<<EOF
The Chrysler Building, the famous art deco New York skyscraper, will be sold for a small fraction of its previous sales price.
The deal, first reported by The Real Deal, was for $150 million, according to a source familiar with the deal.
Mubadala, an Abu Dhabi investment fund, purchased 90% of the building for $800 million in 2008.
Real estate firm Tishman Speyer had owned the other 10%.
The buyer is RFR Holding, a New York real estate company.
Officials with Tishman and RFR did not immediately respond to a request for comments.
It'\''s unclear when the deal will close.
The building sold fairly quickly after being publicly placed on the market only two months ago.
The sale was handled by CBRE Group.
The incentive to sell the building at such a huge loss was due to the soaring rent the owners pay to Cooper Union, a New York college, for the land under the building.
The rent is rising from $7.75 million last year to $32.5 million this year to $41 million in 2028.
Meantime, rents in the building itself are not rising nearly that fast.
While the building is an iconic landmark in the New York skyline, it is competing against newer office towers with large floor-to-ceiling windows and all the modern amenities.
Still the building is among the best known in the city, even to people who have never been to New York.
It is famous for its triangle-shaped, vaulted windows worked into the stylized crown, along with its distinctive eagle gargoyles near the top.
It has been featured prominently in many films, including Men in Black 3, Spider-Man, Armageddon, Two Weeks Notice and Independence Day.
The previous sale took place just before the 2008 financial meltdown led to a plunge in real estate prices.
Still there have been a number of high profile skyscrapers purchased for top dollar in recent years, including the Waldorf Astoria hotel, which Chinese firm Anbang Insurance purchased in 2016 for nearly $2 billion, and the Willis Tower in Chicago, which was formerly known as Sears Tower, once the world'\''s tallest.
Blackstone Group (BX) bought it for $1.3 billion 2015.
The Chrysler Building was the headquarters of the American automaker until 1953, but it was named for and owned by Chrysler chief Walter Chrysler, not the company itself.
Walter Chrysler had set out to build the tallest building in the world, a competition at that time with another Manhattan skyscraper under construction at 40 Wall Street at the south end of Manhattan. He kept secret the plans for the spire that would grace the top of the building, building it inside the structure and out of view of the public until 40 Wall Street was complete.
Once the competitor could rise no higher, the spire of the Chrysler building was raised into view, giving it the title.
EOF;
		// lets post the valid content to api to return a valid excerpt from the server.
		$user_id = $this->factory->user->create( array( 'role' => 'author' ) );
		wp_set_current_user( $user_id );
		$post_id = $this->factory->post->create();
		$url     = $this->post_excerpt_rest_route . '/' . $post_id;
		$request = new WP_REST_Request( 'POST', $url );
		$request->set_header( 'content-type', 'application/json' );
		$request->set_body( wp_json_encode( array('post_body' => $valid_content) ) );
		$response      = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		if($response_data['status'] != 'success'){
			$this->markTestSkipped('Possible issue reaching `https://api.wordlift.io/summarize`');
		}
		$this->assertEquals( $response_data['status'], 'success');
	}

	/**
	 * When the duplicate request with same body, then it should verify the hash in meta and deliever the response.
	 */
	public function test_excerpt_caching_working_correctly() {
		$valid_content = <<<EOF
The Chrysler Building, the famous art deco New York skyscraper, will be sold for a small fraction of its previous sales price.
The deal, first reported by The Real Deal, was for $150 million, according to a source familiar with the deal.
Mubadala, an Abu Dhabi investment fund, purchased 90% of the building for $800 million in 2008.
Real estate firm Tishman Speyer had owned the other 10%.
The buyer is RFR Holding, a New York real estate company.
Officials with Tishman and RFR did not immediately respond to a request for comments.
It'\''s unclear when the deal will close.
The building sold fairly quickly after being publicly placed on the market only two months ago.
The sale was handled by CBRE Group.
The incentive to sell the building at such a huge loss was due to the soaring rent the owners pay to Cooper Union, a New York college, for the land under the building.
The rent is rising from $7.75 million last year to $32.5 million this year to $41 million in 2028.
Meantime, rents in the building itself are not rising nearly that fast.
While the building is an iconic landmark in the New York skyline, it is competing against newer office towers with large floor-to-ceiling windows and all the modern amenities.
Still the building is among the best known in the city, even to people who have never been to New York.
It is famous for its triangle-shaped, vaulted windows worked into the stylized crown, along with its distinctive eagle gargoyles near the top.
It has been featured prominently in many films, including Men in Black 3, Spider-Man, Armageddon, Two Weeks Notice and Independence Day.
The previous sale took place just before the 2008 financial meltdown led to a plunge in real estate prices.
Still there have been a number of high profile skyscrapers purchased for top dollar in recent years, including the Waldorf Astoria hotel, which Chinese firm Anbang Insurance purchased in 2016 for nearly $2 billion, and the Willis Tower in Chicago, which was formerly known as Sears Tower, once the world'\''s tallest.
Blackstone Group (BX) bought it for $1.3 billion 2015.
The Chrysler Building was the headquarters of the American automaker until 1953, but it was named for and owned by Chrysler chief Walter Chrysler, not the company itself.
Walter Chrysler had set out to build the tallest building in the world, a competition at that time with another Manhattan skyscraper under construction at 40 Wall Street at the south end of Manhattan. He kept secret the plans for the spire that would grace the top of the building, building it inside the structure and out of view of the public until 40 Wall Street was complete.
Once the competitor could rise no higher, the spire of the Chrysler building was raised into view, giving it the title.
EOF;
		// lets post the valid content to api to return a valid excerpt from the server.
		$user_id = $this->factory->user->create( array( 'role' => 'author' ) );
		wp_set_current_user( $user_id );
		$post_id = $this->factory->post->create();
		$url     = $this->post_excerpt_rest_route . '/' . $post_id;
		$request = new WP_REST_Request( 'POST', $url );
		$request->set_header( 'content-type', 'application/json' );
		$request->set_body( wp_json_encode( array('post_body' => $valid_content) ) );
		$response      = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		if($response_data['status'] != 'success'){
			$this->markTestSkipped('Possible issue reaching `https://api.wordlift.io/summarize`');
		}
		$this->assertEquals( $response_data['status'], 'success');
		// Now we should have an entry for this meta.
		$cache_data = get_post_meta($post_id, Post_Excerpt_Rest_Controller::POST_EXCERPT_META_KEY, true);
		$this->assertEquals( true, is_array($cache_data));
		// Send another request and check whether if we have cached data getting returned.
		$response      = $this->server->dispatch( $request );
		$response_data = $response->get_data();
		$this->assertEquals( $response_data['from_cache'], true);
	}
}
