<?php

use Wordlift\FAQ\Faq_Content_Filter;


/**
 * Tests: Tests the FAQ content filter.
 * @since 3.26.0
 * @package wordlift
 * @subpackage wordlift/tests
 *
 */

class Test_Faq_Content_Filter extends  Wordlift_Unit_Test_Case{
	/**
	 * @var Faq_Content_Filter Content filter instance.
	 */
	private $instance;

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->instance = new Faq_Content_Filter();
	}

	/**
	 * Test if the class exists.
	 */
	public function testInstanceShouldNotBeNull() {
		$this->assertNotNull(new Faq_Content_Filter());
	}

	public function testGivenSingleHighligtShouldRemoveItCorrectly() {
		$src = <<<EOF
		<p>sdfljsdlfkjs pwiqeop
			<span class="wl-faq-highlight" style="background-color: #ffff00;">
				text to be highlighted
			</span>oeiwpqoe  wqerwqewqedd hi hi
		<p>
EOF;
		$result = $this->instance->filter_post_content( $src );
		$expected_result = <<<EOF
		<p>sdfljsdlfkjs pwiqeop text to be highlighted oeiwpqoe  wqerwqewqedd hi hi
        </p><p></p>
EOF;
		$result = preg_replace('/\s+/','',$result);
		$expected_result = preg_replace('/\s+/','',$expected_result);
		$this->assertEquals($result,$expected_result);

	}
}