<?php
/**
 * Define the Wordlift_Entity_Service_Test class.
 *
 * @since 3.29.0
 * @group entity
 */
class Wordlift_Entity_Rest_Service extends Wordlift_Unit_Test_Case {


	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		global $wp_filter;
		$wp_filter = array();
		run_wordlift();
	}

	public function test_when_entity_is_saved_with_wlEntityMainType_set_should_set_the_taxonomy_type() {
		// We created an entity.
		$entity_id = $this->factory()->post->create(array('post_type' => 'entity'));


		$request = new \WP_REST_Request();

		$request->set_param('wlEntityMainType', 'http://schema.org/LocalBusiness');

		do_action( "rest_insert_entity", get_post( $entity_id ), $request, true );

		// now check if we have the term http://schema.org/LocalBusiness in the entity.
		$terms = wp_get_post_terms($entity_id, 'wl_entity_type');
		$this->assertCount(1, $terms, 'Entity should be set to LocalBusiness' );
		$target_term  =$terms[0];

		$this->assertEquals( 'LocalBusiness', $target_term->name);
	}


}