services:
  Wordlift\Modules\Super_Resolution\Attachment_Field:
    class: Wordlift\Modules\Super_Resolution\Attachment_Field

  Wordlift\Modules\Super_Resolution\Super_Resolution_Controller:
    class: Wordlift\Modules\Super_Resolution\Super_Resolution_Controller
