// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $(function() {
    return $("#wordlift-bar-switch").click(function() {
      return $("#wordlift-bar").toggleClass("closed");
    });
  });

}).call(this);
