services:
  Wordlift\Modules\Acf4so\Quiet_Skin:
    class: \Wordlift\Modules\Acf4so\Quiet_Skin
  Plugin_Upgrader:
    class: \Plugin_Upgrader
    arguments: [ '@Wordlift\Modules\Acf4so\Quiet_Skin' ]
  Wordlift\Modules\Acf4so\Remote_Plugin:
    class: \Wordlift\Modules\Acf4so\Remote_Plugin
    arguments: [ 'advanced-custom-fields-for-schema-org/advanced-custom-fields-for-schema-org.php', 'advanced-custom-fields-for-schema-org', 'https://wordlift.io/wp-content/uploads/advanced-custom-fields-for-schema-org/advanced-custom-fields-for-schema-org.zip' ]
  Wordlift\Modules\Acf4so\Installer:
    arguments: ['@Plugin_Upgrader', '@Wordlift\Modules\Acf4so\Remote_Plugin']
    class: \Wordlift\Modules\Acf4so\Installer
  Wordlift\Modules\Acf4so\Notices:
    arguments: ['@Wordlift\Modules\Acf4so\Remote_Plugin']
    class: \Wordlift\Modules\Acf4so\Notices