openapi: 3.1.0
info:
  title: WordLift Plugin Google Organization Knowledge Panel API
  description: The Google Organization KP API provides endpoints to prepopulate form fields and handle save on the Wordlift Google Organization Knowledge Panel. 
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /wordlift/v1/google-organization-kp/pages
    get:
      operationId: listPages
      summary: List of pages
      description: Returns a list of pages
      responses:
        "200":
          description: The list of pages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPagesResponse'
        "404":
          description: No pages were found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPagesError'
  /wordlift/v1/google-organization-kp/countries
    get:
      operationId: listCountries
      summary: List of countries
      description: Returns a list of countries
      responses:
        "200":
          description: The list of countries
          content:
  /wordlift/v1/google-organization-kp/form-data
    get:
      operationId: listFormData
      summary: Retrieve existing form data
      description: Return array of existing data for the form fields if exists
      responses:
        "200":
          description: Array of field names and data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListFormDataResponse"
        "404":
          description: No existing data was found
          content:
    put:
      operationId: saveFormData
      summary: Save form data
      description: Return array of existing data for the form fields
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TermMatch"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  schemas:
    ListPagesResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
    ListPagesError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        status:
          type: integer
          format: int32
    ListCountriesResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        name:
          type: string