openapi: 3.1.0
info:
  title: WordLift Plugin Google Organization Knowledge Panel API
  description: The Google Organization KP API provides various endpoints useful for the Organization page on the Wordlift Dashboard.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /wordlift/v1/wl-google-organization-kp/pages:
    get:
      operationId: listPages
      summary: List of Pages
      parameters:
        - name: pagination
          in: query
          required: false
          description: Pagination page number
          schema:
            type: integer
        - name: title_starts_with
          in: query
          required: false
          description: Case-insensitive string to filter Pages by title
          schema:
            type: string
      responses:
        "200":
          description: The list of pages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
        "400":
          description: Error
        "401":
          description: Forbidden
  /wordlift/v1/wl-google-organization-kp/countries:
    get:
      operationId: listCountries
      summary: List of countries
      responses:
        "200":
          description: The list of countries
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  eg: Egypt
                  it: Italy
        "401":
          description: Forbidden
  /wordlift/v1/wl-google-organization-kp/data:
    get:
      operationId: listFormData
      summary: Retrieve existing form data
      responses:
        "200":
          description: Array of field names and data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/formData'
        "400":
          description: Error
        "401":
          description: Forbidden
        "404":
          description: Data not found
    post:
      operationId: saveFormData
      summary: Save form data
      description: Return array of existing data for the form fields
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                description:
                  type: string
                alt_name:
                  type: string
                legal_name:
                  type: string
                image:
                  type: string
                  format: binary
                same_as:
                  type: array
                  items:
                    type: string
                address:
                  type: string
                locality:
                  type: string
                region:
                  type: string
                country:
                  type: string
                postal_code:
                  type: string
                telephone:
                  type: string
                email:
                  type: string
                  format: email
                no_employees:
                  type: integer
                founding_date:
                  type: string
                  format: date
                iso_6523:
                  type: string
                naics:
                  type: string
                global_loc_no:
                  type: string
                vat_id:
                  type: string
                tax_id:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/formData'
        "400":
          description: Error
        "401":
          description: Forbidden
components:
  schemas:
    formData:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        description:
          type: string
        alt_name:
          type: string
        legal_name:
          type: string
        image:
          type: string
        same_as:
          type: array
          items:
            type: string
        address:
          type: string
        locality:
          type: string
        region:
          type: string
        country:
          type: string
        postal_code:
          type: string
        telephone:
          type: string
        email:
          type: string
          format: email
        no_employees:
          type: integer
        founding_date:
          type: string
          format: date
        iso_6523:
          type: string
        naics:
          type: string
        global_loc_no:
          type: string
        vat_id:
          type: string
        tax_id:
          type: string
