openapi: 3.0.0
info:
  title: WordLift Plugin Google Organization Knowledge Panel API
  description: The Google Organization KP API provides various endpoints useful for the Organization page on the Wordlift Dashboard.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /wordlift/v1/wl-google-organization-kp/pages:
    get:
      operationId: listPages
      summary: List of Pages
      parameters:
        - name: pagination
          in: query
          required: false
          description: Pagination page number
          schema:
            type: integer
        - name: title_starts_with
          in: query
          required: false
          description: Case-insensitive string to filter Pages by title
          schema:
            type: string
      responses:
        "200":
          description: The list of pages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages'
        "400":
          description: Error
        "401":
          description: Forbidden
  /wordlift/v1/wl-google-organization-kp/countries:
    get:
      operationId: listCountries
      summary: List of countries
      responses:
        "200":
          description: The list of countries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/countries'
        "401":
          description: Forbidden
  /wordlift/v1/wl-google-organization-kp/data:
    get:
      operationId: listFormData
      summary: Retrieve existing form data
      responses:
        "200":
          description: Array of field names and data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/formDataGet'
        "400":
          description: Error
        "401":
          description: Forbidden
        "404":
          description: Data not found
    post:
      operationId: saveFormData
      summary: Save form data
      description: Return array of existing data for the form fields
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/formDataPost'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/formDataGet'
        "400":
          description: Error
        "401":
          description: Forbidden
components:
  schemas:
    pages:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          title:
            type: string
    countries:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          code:
            type: string
    formDataAbstract:
      type: object
      properties:
        page:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
        type:
          type: string
        name:
          type: string
        alt_name:
          type: string
        legal_name:
          type: string
        description:
          type: string
        image:
          type: string
        url:
          type: string
          format: url
        address:
          type: string
        locality:
          type: string
        region:
          type: string
        country:
          type: string
        postal_code:
          type: string
        telephone:
          type: string
        email:
          type: string
          format: email
        no_employees:
          type: integer
        founding_date:
          type: string
          format: date
        iso_6523:
          type: string
        naics:
          type: string
        global_loc_no:
          type: string
        vat_id:
          type: string
        tax_id:
          type: string
    formDataGet:
      allOf:
        - $ref: '#/components/schemas/formDataAbstract'
        - type: object
          properties:
            same_as:
              type: array
              items:
                type: string
                format: url
    formDataPost:
      allOf:
        - $ref: '#/components/schemas/formDataAbstract'
        - type: object
          properties:
            'same_as[]':
              type: array
              items:
                type: string
                format: url