services:
  _defaults: { public: true }
  
  Wordlift\Modules\Google_Organization_Kp\Organization_Knowledge_Panel_Service:
    class: Wordlift\Modules\Google_Organization_Kp\Organization_Knowledge_Panel_Service

  Wordlift\Modules\Google_Organization_Kp\Rest_Controller:
    class: Wordlift\Modules\Google_Organization_Kp\Rest_Controller
    arguments: [ '@Wordlift\Modules\Google_Organization_Kp\Organization_Knowledge_Panel_Service' ]