// Generated by CoffeeScript 1.3.3
(function() {

  (function($) {
    return $(".container.entities").arrowscrollers({
      arrow: {
        width: 36
      },
      marginTop: false
    });
  })(jQuery);

}).call(this);
