// Generated by CoffeeScript 1.4.0
(function() {

  (function($) {
    return $('.entity-container').arrowscrollers({
      settings: {
        arrow: {
          width: 36
        }
      }
    });
  })(jQuery);

}).call(this);
