#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR -- '***.php' |  tr '\n' ' ' | paste -sd ' ')



if [ -n "$FILES" ]; then
  echo "$FILES" | xargs ./vendor/bin/phpcbf --standard=phpcs.xml.dist
fi
