#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR -- '***.php' | sed 's| |\\ |g')


#
#if [ -n "$FILES" ]; then
#  ./vendor/bin/phpcbf --standard=phpcs.xml.dist "$FILES"
#fi
