name: Adthrive

on:
  push:
    branches:
      - master
      - "feature/1632-white-labeling"

jobs:
  adthrive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Publish
        run: ./.github/workflows/adthrive.sh
        env:
          AZURE_STORAGE_SHARED_KEY_QUERY_PARAM: ${{ secrets.AZURE_STORAGE_SHARED_KEY_QUERY_PARAM }}
